export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST'
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS'
export const POST_LOGIN_FAILED = 'POST_LOGIN_FAILED'

export const POST_LOGOUT_REQUEST = 'POST_LOGOUT_REQUEST'
export const POST_LOGOUT_SUCCESS = 'POST_LOGOUT_SUCCESS'
export const POST_LOGOUT_FAILED = 'POST_LOGOUT_FAILED'

export const POST_SIGNUP_REQUEST = 'POST_SIGNUP_REQUEST'
export const POST_SIGNUP_SUCCESS = 'POST_SIGNUP_SUCCESS'
export const POST_SIGNUP_FAILED = 'POST_SIGNUP_FAILED'

export const FETCH_REQUEST = 'FETCH_REQUEST'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAILED = 'FETCH_FAILED'

export const POST_UPLOAD_REQUEST = 'POST_UPLOAD_REQUEST'
export const POST_UPLOAD_SUCCESS = 'POST_UPLOAD_SUCCESS'
export const POST_UPLOAD_FAILED = 'POST_UPLOAD_FAILED'

export const GET_USERINFO_REQUEST = 'GET_USERINFO_REQUEST'
export const GET_USERINFO_SUCCESS = 'GET_USERINFO_SUCCESS'
export const GET_USERINFO_FAILED = 'GET_USERINFO_FAILED'

export const PUT_USERINFO_REQUEST = 'PUT_USERINFO_REQUEST'
export const PUT_USERINFO_SUCCESS = 'PUT_USERINFO_SUCCESS'
export const PUT_USERINFO_FAILED = 'PUT_USERINFO_FAILED'

export const GET_HOME_RECRUIT_ORDER_LIST_REQUEST = 'GET_HOME_RECRUIT_ORDER_LIST_REQUEST'
export const GET_HOME_RECRUIT_ORDER_LIST_SUCCESS = 'GET_HOME_RECRUIT_ORDER_LIST_SUCCESS'
export const GET_HOME_RECRUIT_ORDER_LIST_FAILED = 'GET_HOME_RECRUIT_ORDER_LIST_FAILED'

export const GET_ACCOUNT_RECRUIT_ORDER_LIST_REQUEST = 'GET_ACCOUNT_RECRUIT_ORDER_LIST_REQUEST'
export const GET_ACCOUNT_RECRUIT_ORDER_LIST_SUCCESS = 'GET_ACCOUNT_RECRUIT_ORDER_LIST_SUCCESS'
export const GET_ACCOUNT_RECRUIT_ORDER_LIST_FAILED = 'GET_ACCOUNT_RECRUIT_ORDER_LIST_FAILED'

export const GET_RECRUIT_ORDER_DETAIL_REQUEST = 'GET_RECRUIT_ORDER_DETAIL_REQUEST'
export const GET_RECRUIT_ORDER_DETAIL_SUCCESS = 'GET_RECRUIT_ORDER_DETAIL_SUCCESS'
export const GET_RECRUIT_ORDER_DETAIL_FAILED = 'GET_RECRUIT_ORDER_DETAIL_FAILED'

export const POST_RECRUIT_ORDER_REQUEST = 'POST_RECRUIT_ORDER_REQUEST'
export const POST_RECRUIT_ORDER_SUCCESS = 'POST_RECRUIT_ORDER_SUCCESS'
export const POST_RECRUIT_ORDER_FAILED = 'POST_RECRUIT_ORDER_FAILED'

export const PUT_RECRUIT_ORDER_REQUEST = 'PUT_RECRUIT_ORDER_REQUEST'
export const PUT_RECRUIT_ORDER_SUCCESS = 'PUT_RECRUIT_ORDER_SUCCESS'
export const PUT_RECRUIT_ORDER_FAILED = 'PUT_RECRUIT_ORDER_FAILED'

export const DELETE_RECRUIT_ORDER_REQUEST = 'DELETE_RECRUIT_ORDER_REQUEST'
export const DELETE_RECRUIT_ORDER_SUCCESS = 'DELETE_RECRUIT_ORDER_SUCCESS'
export const DELETE_RECRUIT_ORDER_FAILED = 'POST_RECRUIT_ORDER_FAILED'

export const GET_HOME_GROUP_ORDER_LIST_REQUEST = 'GET_HOME_GROUP_ORDER_LIST_REQUEST'
export const GET_HOME_GROUP_ORDER_LIST_SUCCESS = 'GET_HOME_GROUP_ORDER_LIST_SUCCESS'
export const GET_HOME_GROUP_ORDER_LIST_FAILED = 'GET_HOME_GROUP_ORDER_LIST_FAILED'

export const GET_ACCOUNT_GROUP_ORDER_LIST_REQUEST = 'GET_ACCOUNT_GROUP_ORDER_LIST_REQUEST'
export const GET_ACCOUNT_GROUP_ORDER_LIST_SUCCESS = 'GET_ACCOUNT_GROUP_ORDER_LIST_SUCCESS'
export const GET_ACCOUNT_GROUP_ORDER_LIST_FAILED = 'GET_ACCOUNT_GROUP_ORDER_LIST_FAILED'

export const GET_GROUP_ORDER_DETAIL_REQUEST = 'GET_GROUP_ORDER_DETAIL_REQUEST'
export const GET_GROUP_ORDER_DETAIL_SUCCESS = 'GET_GROUP_ORDER_DETAIL_SUCCESS'
export const GET_GROUP_ORDER_DETAIL_FAILED = 'GET_GROUP_ORDER_DETAIL_FAILED'

export const POST_GROUP_ORDER_REQUEST = 'POST_GROUP_ORDER_REQUEST'
export const POST_GROUP_ORDER_SUCCESS = 'POST_GROUP_ORDER_SUCCESS'
export const POST_GROUP_ORDER_FAILED = 'POST_GROUP_ORDER_FAILED'

export const PUT_GROUP_ORDER_REQUEST = 'PUT_GROUP_ORDER_REQUEST'
export const PUT_GROUP_ORDER_SUCCESS = 'PUT_GROUP_ORDER_SUCCESS'
export const PUT_GROUP_ORDER_FAILED = 'PUT_GROUP_ORDER_FAILED'

export const DELETE_GROUP_ORDER_REQUEST = 'DELETE_GROUP_ORDER_REQUEST'
export const DELETE_GROUP_ORDER_SUCCESS = 'DELETE_GROUP_ORDER_SUCCESS'
export const DELETE_GROUP_ORDER_FAILED = 'POST_GROUP_ORDER_FAILED'

export const GET_HOME_WAR_ORDER_LIST_REQUEST = 'GET_HOME_WAR_ORDER_LIST_REQUEST'
export const GET_HOME_WAR_ORDER_LIST_SUCCESS = 'GET_HOME_WAR_ORDER_LIST_SUCCESS'
export const GET_HOME_WAR_ORDER_LIST_FAILED = 'GET_HOME_WAR_ORDER_LIST_FAILED'

export const GET_ACCOUNT_WAR_ORDER_LIST_REQUEST = 'GET_ACCOUNT_WAR_ORDER_LIST_REQUEST'
export const GET_ACCOUNT_WAR_ORDER_LIST_SUCCESS = 'GET_ACCOUNT_WAR_ORDER_LIST_SUCCESS'
export const GET_ACCOUNT_WAR_ORDER_LIST_FAILED = 'GET_ACCOUNT_WAR_ORDER_LIST_FAILED'

export const GET_WAR_ORDER_DETAIL_REQUEST = 'GET_WAR_ORDER_DETAIL_REQUEST'
export const GET_WAR_ORDER_DETAIL_SUCCESS = 'GET_WAR_ORDER_DETAIL_SUCCESS'
export const GET_WAR_ORDER_DETAIL_FAILED = 'GET_WAR_ORDER_DETAIL_FAILED'

export const POST_WAR_ORDER_REQUEST = 'POST_WAR_ORDER_REQUEST'
export const POST_WAR_ORDER_SUCCESS = 'POST_WAR_ORDER_SUCCESS'
export const POST_WAR_ORDER_FAILED = 'POST_WAR_ORDER_FAILED'

export const PUT_WAR_ORDER_REQUEST = 'PUT_WAR_ORDER_REQUEST'
export const PUT_WAR_ORDER_SUCCESS = 'PUT_WAR_ORDER_SUCCESS'
export const PUT_WAR_ORDER_FAILED = 'PUT_WAR_ORDER_FAILED'

export const DELETE_WAR_ORDER_REQUEST = 'DELETE_WAR_ORDER_REQUEST'
export const DELETE_WAR_ORDER_SUCCESS = 'DELETE_WAR_ORDER_SUCCESS'
export const DELETE_WAR_ORDER_FAILED = 'POST_WAR_ORDER_FAILED'

export const GET_HOME_RESUME_ORDER_LIST_REQUEST = 'GET_HOME_RESUME_ORDER_LIST_REQUEST'
export const GET_HOME_RESUME_ORDER_LIST_SUCCESS = 'GET_HOME_RESUME_ORDER_LIST_SUCCESS'
export const GET_HOME_RESUME_ORDER_LIST_FAILED = 'GET_HOME_RESUME_ORDER_LIST_FAILED'

export const GET_ACCOUNT_RESUME_ORDER_LIST_REQUEST = 'GET_ACCOUNT_RESUME_ORDER_LIST_REQUEST'
export const GET_ACCOUNT_RESUME_ORDER_LIST_SUCCESS = 'GET_ACCOUNT_RESUME_ORDER_LIST_SUCCESS'
export const GET_ACCOUNT_RESUME_ORDER_LIST_FAILED = 'GET_ACCOUNT_RESUME_ORDER_LIST_FAILED'

export const GET_RESUME_ORDER_DETAIL_REQUEST = 'GET_RESUME_ORDER_DETAIL_REQUEST'
export const GET_RESUME_ORDER_DETAIL_SUCCESS = 'GET_RESUME_ORDER_DETAIL_SUCCESS'
export const GET_RESUME_ORDER_DETAIL_FAILED = 'GET_RESUME_ORDER_DETAIL_FAILED'

export const POST_RESUME_ORDER_REQUEST = 'POST_RESUME_ORDER_REQUEST'
export const POST_RESUME_ORDER_SUCCESS = 'POST_RESUME_ORDER_SUCCESS'
export const POST_RESUME_ORDER_FAILED = 'POST_RESUME_ORDER_FAILED'

export const PUT_RESUME_ORDER_REQUEST = 'PUT_RESUME_ORDER_REQUEST'
export const PUT_RESUME_ORDER_SUCCESS = 'PUT_RESUME_ORDER_SUCCESS'
export const PUT_RESUME_ORDER_FAILED = 'PUT_RESUME_ORDER_FAILED'

export const DELETE_RESUME_ORDER_REQUEST = 'DELETE_RESUME_ORDER_REQUEST'
export const DELETE_RESUME_ORDER_SUCCESS = 'DELETE_RESUME_ORDER_SUCCESS'
export const DELETE_RESUME_ORDER_FAILED = 'POST_RESUME_ORDER_FAILED'

export const POST_TEAMS_REQUEST = 'POST_TEAMS_REQUEST'
export const POST_TEAMS_SUCCESS = 'POST_TEAMS_SUCCESS'
export const POST_TEAMS_FAILED = 'POST_TEAMS_FAILED'

export const PUT_TEAMS_REQUEST = 'PUT_TEAMS_REQUEST'
export const PUT_TEAMS_SUCCESS = 'PUT_TEAMS_SUCCESS'
export const PUT_TEAMS_FAILED = 'PUT_TEAMS_FAILED'

export const GET_MY_TEAMS_REQUEST = 'GET_MY_TEAMS_REQUEST'
export const GET_MY_TEAMS_SUCCESS = 'GET_MY_TEAMS_SUCCESS'
export const GET_MY_TEAMS_FAILED = 'GET_MY_TEAMS_FAILED'

export const GET_IN_TEAMS_REQUEST = 'GET_IN_TEAMS_REQUEST'
export const GET_IN_TEAMS_SUCCESS = 'GET_IN_TEAMS_SUCCESS'
export const GET_IN_TEAMS_FAILED = 'GET_IN_TEAMS_FAILED'

export const DELETE_TEAM_MEMBER_REQUEST = 'DELETE_TEAM_MEMBER_REQUEST'
export const DELETE_TEAM_MEMBER_SUCCESS = 'DELETE_TEAM_MEMBER_SUCCESS'
export const DELETE_TEAM_MEMBER_FAILED = 'DELETE_TEAM_MEMBER_FAILED'

export const DELETE_TEAM_REQUEST = 'DELETE_TEAM_REQUEST'
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS'
export const DELETE_TEAM_FAILED = 'DELETE_TEAM_FAILED'

export const GET_STICKY_ARTICLES_REQUEST = 'GET_STICKY_ARTICLES_REQUEST'
export const GET_STICKY_ARTICLES_SUCCESS = 'GET_STICKY_ARTICLES_SUCCESS'
export const GET_STICKY_ARTICLES_FAILED = 'GET_STICKY_ARTICLES_FAILED'

export const GET_HOME_USERINFO_DETAIL_REQUEST = 'GET_HOME_USERINFO_DETAIL_REQUEST'
export const GET_HOME_USERINFO_DETAIL_SUCCESS = 'GET_HOME_USERINFO_DETAIL_SUCCESS'
export const GET_HOME_USERINFO_DETAIL_FAILED = 'GET_HOME_USERINFO_DETAIL_FAILED'

export const GET_HOME_USERINFO_LIST_REQUEST = 'GET_HOME_USERINFO_LIST_REQUEST'
export const GET_HOME_USERINFO_LIST_SUCCESS = 'GET_HOME_USERINFO_LIST_SUCCESS'
export const GET_HOME_USERINFO_LIST_FAILED = 'GET_HOME_USERINFO_LIST_FAILED'

export const GET_HOME_TEAM_DETAIL_REQUEST = 'GET_HOME_TEAM_DETAIL_REQUEST'
export const GET_HOME_TEAM_DETAIL_SUCCESS = 'GET_HOME_TEAM_DETAIL_SUCCESS'
export const GET_HOME_TEAM_DETAIL_FAILED = 'GET_HOME_TEAM_DETAIL_FAILED'

export const GET_HOME_TEAM_LIST_REQUEST = 'GET_HOME_TEAM_LIST_REQUEST'
export const GET_HOME_TEAM_LIST_SUCCESS = 'GET_HOME_TEAM_LIST_SUCCESS'
export const GET_HOME_TEAM_LIST_FAILED = 'GET_HOME_TEAM_LIST_FAILED'

export const SEND_EMAIL_REQUEST = 'SEND_EMAIL_REQUEST'
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS'
export const SEND_EMAIL_FAILED = 'SEND_EMAIL_FAILED'

export const SEND_PASSWORD_RESET_REQUEST = 'SEND_PASSWORD_RESET_REQUEST'
export const SEND_PASSWORD_RESET_SUCCESS = 'SEND_PASSWORD_RESET_SUCCESS'
export const SEND_PASSWORD_RESET_FAILED = 'SEND_PASSWORD_RESET_FAILED'